name: Daily Blog Update and Deploy

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 08:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask schedule requests beautifulsoup4 feedparser google-generativeai stability-sdk

      # Run the Flask app to generate blog posts
      - name: Generate Blog Posts
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}
        run: |
          python app.py &
          sleep 60  # Wait for the app to generate the blog post (adjust as needed)
          pkill -f "python app.py"  # Stop the Flask app

      # Commit and push changes
      - name: Commit Updated Files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add index.html static/images/*
          git commit -m "Daily blog update: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages  # Deploys to the gh-pages branch